### ISSUE TITLE
GPU support tensors

### ISSUE THREAD

**Issue by karl-richter** [ourownstory/neural_prophet#1002]
NeuralProphet does seem to raise an error when training on GPU's.

        running with CUDA does not work: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0!

_Originally posted by @geneman in https://github.com/ourownstory/neural_prophet/issues/961#issuecomment-1331144742_

**Comment by karl-richter** [comment]
@geneman thanks for raising this issue, I will look into this.

**Comment by karl-richter** [comment]
@geneman, the issue is fixed by #1010, we plan to merge the pr for 0.5.0 which is planned to release next week.

**Comment by geneman** [comment]
@karl-richter , still getting the error
  File "C:\Python39\lib\site-packages\neuralprophet\forecaster.py", line 731, in fit
    metrics_df = self._train(df, minimal=minimal, continue_training=continue_training)
                 │    │      │           │                          └ False
                 │    │      │           └ False
                 │    │      └              ds          y      ID
                 │    │        0    2018-01-01  16.752917  __df__
                 │    │        1    2018-01-02  16.950081  __df__
                 │    │        2    2018-01-03  17....
                 │    └ <function NeuralProphet._train at 0x000001A98B6C5820>
                 └ <neuralprophet.forecaster.NeuralProphet object at 0x000001A99ADCA1F0>

  File "C:\Python39\lib\site-packages\neuralprophet\forecaster.py", line 2564, in _train
    self.trainer.fit(
    │    │       └ <function Trainer.fit at 0x000001A98A29E4C0>
    │    └ <pytorch_lightning.trainer.trainer.Trainer object at 0x000001A99AED4EB0>
    └ <neuralprophet.forecaster.NeuralProphet object at 0x000001A99ADCA1F0>

  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
    │    └ <function Trainer._call_and_handle_interrupt at 0x000001A98A29E430>
    └ <pytorch_lightning.trainer.trainer.Trainer object at 0x000001A99AED4EB0>

  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           │           │       └ {}
           │           └ (TimeNet(
           │               (metrics_train): MetricCollection(
           │                 (MAE): MeanAbsoluteError()
           │                 (RMSE): MeanSquaredError()
           │               )
           │               (metrics_v...
           └ <bound method Trainer._fit_impl of <pytorch_lightning.trainer.trainer.Trainer object at 0x000001A99AED4EB0>>

  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
              │    │    │                │    └ <property object at 0x000001A98A2A5A40>
              │    │    │                └ <pytorch_lightning.trainer.trainer.Trainer object at 0x000001A99AED4EB0>
              │    │    └ TimeNet(
              │    │        (metrics_train): MetricCollection(
              │    │          (MAE): MeanAbsoluteError()
              │    │          (RMSE): MeanSquaredError()
              │    │        )
              │    │        (metrics_va...
              │    └ <function Trainer._run at 0x000001A98A29EA60>
              └ <pytorch_lightning.trainer.trainer.Trainer object at 0x000001A99AED4EB0>

  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1166, in _run
    results = self._run_stage()
              │    └ <function Trainer._run_stage at 0x000001A98A29ECA0>
              └ <pytorch_lightning.trainer.trainer.Trainer object at 0x000001A99AED4EB0>

  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1252, in _run_stage
    return self._run_train()
           │    └ <function Trainer._run_train at 0x000001A98A29EDC0>
           └ <pytorch_lightning.trainer.trainer.Trainer object at 0x000001A99AED4EB0>

  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1283, in _run_train
    self.fit_loop.run()
    │    └ <property object at 0x000001A98A2A5CC0>
    └ <pytorch_lightning.trainer.trainer.Trainer object at 0x000001A99AED4EB0>

  File "C:\Python39\lib\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
    self.advance(*args, **kwargs)
    │    │        │       └ {}
    │    │        └ ()
    │    └ <function FitLoop.advance at 0x000001A98A1F8790>
    └ <pytorch_lightning.loops.fit_loop.FitLoop object at 0x000001A99AEBBAC0>

  File "C:\Python39\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 271, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
    │    │          │    │          │   │    └ None
    │    │          │    │          │   └ <pytorch_lightning.loops.fit_loop.FitLoop object at 0x000001A99AEBBAC0>
    │    │          │    │          └ <function Loop.run at 0x000001A98A19A0D0>
    │    │          │    └ <pytorch_lightning.loops.epoch.training_epoch_loop.TrainingEpochLoop object at 0x000001A99AEBBB80>
    │    │          └ <pytorch_lightning.loops.fit_loop.FitLoop object at 0x000001A99AEBBAC0>
    │    └ []
    └ <pytorch_lightning.loops.fit_loop.FitLoop object at 0x000001A99AEBBAC0>

  File "C:\Python39\lib\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
    self.advance(*args, **kwargs)
    │    │        │       └ {}
    │    │        └ (<pytorch_lightning.utilities.fetching.DataFetcher object at 0x000001A9A217DA60>,)
    │    └ <function TrainingEpochLoop.advance at 0x000001A98A1EB040>
    └ <pytorch_lightning.loops.epoch.training_epoch_loop.TrainingEpochLoop object at 0x000001A99AEBBB80>

  File "C:\Python39\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 203, in advance
    batch_output = self.batch_loop.run(kwargs)
                   │    │          │   └ OrderedDict([('batch', [OrderedDict([('time', tensor([[0.3934],
                   │    │          │             [0.1069],
                   │    │          │             [0.1469],
                   │    │          │             [0.8866],
                   │    │          │            ...
                   │    │          └ <function Loop.run at 0x000001A98A19A0D0>
                   │    └ <pytorch_lightning.loops.batch.training_batch_loop.TrainingBatchLoop object at 0x000001A9A2147B50>
                   └ <pytorch_lightning.loops.epoch.training_epoch_loop.TrainingEpochLoop object at 0x000001A99AEBBB80>

  File "C:\Python39\lib\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
    self.advance(*args, **kwargs)
    │    │        │       └ {}
    │    │        └ (OrderedDict([('batch', [OrderedDict([('time', tensor([[0.3934],
    │    │                  [0.1069],
    │    │                  [0.1469],
    │    │                  [0.8866],
    │    │                ...
    │    └ <function TrainingBatchLoop.advance at 0x000001A98A1C2550>
    └ <pytorch_lightning.loops.batch.training_batch_loop.TrainingBatchLoop object at 0x000001A9A2147B50>

  File "C:\Python39\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 89, in advance
    outputs = self.manual_loop.run(kwargs)
              │    │           │   └ OrderedDict([('batch', [OrderedDict([('time', tensor([[0.3934],
              │    │           │             [0.1069],
              │    │           │             [0.1469],
              │    │           │             [0.8866],
              │    │           │            ...
              │    │           └ <function Loop.run at 0x000001A98A19A0D0>
              │    └ <pytorch_lightning.loops.optimization.manual_loop.ManualOptimization object at 0x000001A9A2147F70>
              └ <pytorch_lightning.loops.batch.training_batch_loop.TrainingBatchLoop object at 0x000001A9A2147B50>

  File "C:\Python39\lib\site-packages\pytorch_lightning\loops\loop.py", line 200, in run
    self.advance(*args, **kwargs)
    │    │        │       └ {}
    │    │        └ (OrderedDict([('batch', [OrderedDict([('time', tensor([[0.3934],
    │    │                  [0.1069],
    │    │                  [0.1469],
    │    │                  [0.8866],
    │    │                ...
    │    └ <function ManualOptimization.advance at 0x000001A98A1B7E50>
    └ <pytorch_lightning.loops.optimization.manual_loop.ManualOptimization object at 0x000001A9A2147F70>

  File "C:\Python39\lib\site-packages\pytorch_lightning\loops\optimization\manual_loop.py", line 110, in advance
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
                           │    │                                             │      └ <method 'values' of 'collections.OrderedDict' objects>
                           │    │                                             └ OrderedDict([('batch', [OrderedDict([('time', tensor([[0.3934],
                           │    │                                                       [0.1069],
                           │    │                                                       [0.1469],
                           │    │                                                       [0.8866],
                           │    │                                                      ...
                           │    └ <property object at 0x000001A98A170950>
                           └ <pytorch_lightning.loops.optimization.manual_loop.ManualOptimization object at 0x000001A9A2147F70>

  File "C:\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
             │   │       └ {}
             │   └ ([OrderedDict([('time', tensor([[0.3934],
             │             [0.1069],
             │             [0.1469],
             │             [0.8866],
             │             [0.3887],
             │             [0....
             └ <bound method Strategy.training_step of <pytorch_lightning.strategies.single_device.SingleDeviceStrategy object at 0x000001A9...

  File "C:\Python39\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 358, in training_step
    return self.model.training_step(*args, **kwargs)
           │    │                    │       └ {}
           │    │                    └ ([OrderedDict([('time', tensor([[0.3934],
           │    │                              [0.1069],
           │    │                              [0.1469],
           │    │                              [0.8866],
           │    │                              [0.3887],
           │    │                              [0....
           │    └ <property object at 0x000001A98A018270>
           └ <pytorch_lightning.strategies.single_device.SingleDeviceStrategy object at 0x000001A99AEBB790>

  File "C:\Python39\lib\site-packages\neuralprophet\time_net.py", line 1123, in training_step
    loss, reg_loss = self.loss_func(inputs, predicted, targets)
                     │    │         │       │          └ tensor([[[0.7420]],
                     │    │         │       │            
                     │    │         │       │                    [[0.7514]],
                     │    │         │       │            
                     │    │         │       │                    [[0.6982]],
                     │    │         │       │            
                     │    │         │       │                    [[0.6635]],
                     │    │         │       │            
                     │    │         │       │                    [[0.7710]],
                     │    │         │       │            
                     │    │         │       │                    [[0.0877]],
                     │    │         │       │            ...
                     │    │         │       └ tensor([[[ 0.3352,  0.7566,  0.7908]],
                     │    │         │         
                     │    │         │                 [[ 1.1323,  3.1363,  1.3165]],
                     │    │         │         
                     │    │         │                 [[-1.1680, -0.6040, -1.8399]],
                     │    │         │         
                     │    │         │              ...
                     │    │         └ OrderedDict([('time', tensor([[0.3934],
                     │    │                   [0.1069],
                     │    │                   [0.1469],
                     │    │                   [0.8866],
                     │    │                   [0.3887],
                     │    │                   [0.65...
                     │    └ <function TimeNet.loss_func at 0x000001A98B59D790>
                     └ TimeNet(
                         (metrics_train): MetricCollection(
                           (MAE): MeanAbsoluteError()
                           (RMSE): MeanSquaredError()
                         )
                         (metrics_va...

  File "C:\Python39\lib\site-packages\neuralprophet\time_net.py", line 1102, in loss_func
    loss, reg_loss = self._add_batch_regularizations(loss, self.current_epoch, progress_in_epoch)
    │                │    │                          │     │    │              └ 0.0
    │                │    │                          │     │    └ <property object at 0x000001A98A2ACB80>
    │                │    │                          │     └ TimeNet(
    │                │    │                          │         (metrics_train): MetricCollection(
    │                │    │                          │           (MAE): MeanAbsoluteError()
    │                │    │                          │           (RMSE): MeanSquaredError()
    │                │    │                          │         )
    │                │    │                          │         (metrics_va...
    │                │    │                          └ tensor(0.2697, device='cuda:0', grad_fn=<MeanBackward0>)
    │                │    └ <function TimeNet._add_batch_regularizations at 0x000001A98B59DB80>
    │                └ TimeNet(
    │                    (metrics_train): MetricCollection(
    │                      (MAE): MeanAbsoluteError()
    │                      (RMSE): MeanSquaredError()
    │                    )
    │                    (metrics_va...
    └ tensor(0.2697, device='cuda:0', grad_fn=<MeanBackward0>)

  File "C:\Python39\lib\site-packages\neuralprophet\time_net.py", line 1292, in _add_batch_regularizations
    loss = loss + reg_loss
           │      └ tensor([0.])
           └ tensor(0.2697, device='cuda:0', grad_fn=<MeanBackward0>)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by geneman** [comment]
time_net.py line 1257 - change to `reg_loss = torch.zeros(1, dtype=torch.float, requires_grad=False,  device=self.device)`

**Comment by karl-richter** [comment]
Some tensors still remain on the wrong device.
